function EPGConstants()
{
	//1:VOD播放、2:TV播放、3:NVOD播放、4:TVOD播放、5:片花播放、6:书签播放、 7:时移播放、8:直播频道、轮播频道的节目播放、9:直播频道、轮播频道的节目PVR播放、10:增值业务
	this.PLAY_TYPE_VOD = 1;
	this.PLAY_TYPE_LIVE = 2;
	this.PLAY_TYPE_NVOD = 3;
	this.PLAY_TYPE_TVOD = 4;
	this.PLAY_TYPE_ASSESS = 5;
	this.PLAY_TYPE_BOOKMARK = 6;
	this.PLAY_TYPE_PLTV = 7;
	this.PLAY_TYPE_PROGRAM_NOTPVR = 8;
	this.PLAY_TYPE_PROGRAM_PVR = 9;
	this.PLAY_TYPE_VAS = 10;
	//0:视频VOD、1:视频频道、2:音频频道、3:频道、4:音频VOD、10:VOD、 100:增值业务、200:栏目、300:频道节目、9999:混合内容
	this.CONTENT_TYPE_VOD = 10;
	this.CONTENT_TYPE_CHANNEL = 3;
	this.CONTENT_TYPE_VOD_VIDEO = 0;
	this.CONTENT_TYPE_CHANNEL_VIDEO = 1;
	this.CONTENT_TYPE_VOD_AUDIO = 4;
	this.CONTENT_TYPE_CHANNEL_AUDIO = 2;
	this.CONTENT_TYPE_VAS = 100;
	this.CONTENT_TYPE_SUBJECT = 200;
	this.CONTENT_TYPE_PROGRAM = 300;
	this.CONTENT_TYPE_MIXED = 9999;
	this.CONTENT_TYPE_NOT = -123;
	//(1:VOD、2:LIVETV、3:NVOD、4:PLTV、5:TVOD、6:PVR、7:VAS) 
	this.BUSINESS_TYPE_VOD = 1;
	this.BUSINESS_TYPE_LIVETV = 2;
	this.BUSINESS_TYPE_NVOD = 3;
	this.BUSINESS_TYPE_PLTV = 4;
	this.BUSINESS_TYPE_TVOD = 5;
	this.BUSINESS_TYPE_PVR = 6;
	this.BUSINESS_TYPE_VAS = 7;
	this.BUSINESS_TYPE_NOT = -123;
	this.SUBJECT_TYPE_VOD = 10;
	this.SUBJECT_TYPE_CHANNEL = 3;
	this.SUBJECT_TYPE_VIDEO_VOD = 0;
	this.SUBJECT_TYPE_VIDEO_CHANNEL = 1;
	this.SUBJECT_TYPE_AUDIO_VOD = 4;
	this.SUBJECT_TYPE_AUDIO_CHANNEL = 2;
	this.SUBJECT_TYPE_VAS = 100;
	this.SUBJECT_TYPE_PROGRAM = 300;
	this.SUBJECT_TYPE_MIXED = 9999;
	
	this.VOD_AUTH_QUERYSTR = "PLAYTYPE=" + this.PLAY_TYPE_VOD + "&BUSINESSTYPE=" + this.BUSINESS_TYPE_VOD + "&CONTENTTYPE=" + this.CONTENT_TYPE_VOD;
	this.TVOD_AUTH_QUERYSTR = "PLAYTYPE=" + this.PLAY_TYPE_TVOD + "&BUSINESSTYPE=" + this.BUSINESS_TYPE_TVOD + "&CONTENTTYPE=" + this.CONTENT_TYPE_PROGRAM;
	this.ASSESS_AUTH_QUERYSTR = "PLAY_TYPE=" + this.PLAY_TYPE_ASSESS + "&BUSINESS_TYPE=" + this.BUSINESS_TYPE_VOD + "&CONTENT_TYPE=" + this.CONTENT_TYPE_VOD;
	
	this.VAS_AUTH_QUERYSTR = "PLAY_TYPE=" + this.PLAY_TYPE_VAS + "&BUSINESS_TYPE=" + this.BUSINESS_TYPE_VAS + "&CONTENT_TYPE=" + this.CONTENT_TYPE_VAS;
	
}
var EPGConstants = new EPGConstants();